---
title: "Table 1"
author: "Sachin J Shah"
date: "May 13, 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r t1full}

library(haven)
library(tidyverse)
t1 <- read_sas("table1.sas7bdat", NULL)

t1$AGE <- as.numeric(t1$AGE)
t1$LIVSIB <- as.numeric(t1$LIVSIB)
t1$LB001B <- as.numeric(t1$LB001B)
t1$LB001F <- as.numeric(t1$LB001F)

myVars <- c(  "AGE", "RAFEMALE", "race", "RAHISPAN", "poorhealth", "PAIN", "DIABETES", "CANCER", "HEARTD", "STROKE",
              "ARTHRITIS", "DEPRESSION", "SMOKING", "ADLhelp", "cog_status", "BADVISION", "BADHEARING", "local_area_litter",
              "low_fin_control", "vet", "combat", "LB039C", "not_sat_retirement", "edu", "married", "children", "friends", 
              "LIVSIB", "talk_with_someone", "LB001B", "never_charity_work", "LB001F", "children_lt_yearly", "write_friends",
              "lonely", "z_in_tune", "LB020J", "never_less_respect", "never_not_smart", "WORK")

catVars <- c(  "RAFEMALE", "race", "RAHISPAN", "poorhealth", "PAIN", "DIABETES", "CANCER", "HEARTD", "STROKE", "ARTHRITIS",
               "DEPRESSION", "SMOKING", "ADLhelp", "cog_status", "BADVISION", "BADHEARING", "local_area_litter", "low_fin_control",
               "vet", "combat", "not_sat_retirement", "edu", "married", "children", "friends", "talk_with_someone",
               "never_charity_work",  "children_lt_yearly", "write_friends", "lonely", "z_in_tune", "LB020J",
               "never_less_respect", "never_not_smart", "WORK")

not_nl <- c( "AGE", "LB039C", "LIVSIB", "LB001B", "LB001F")


library(labelled)
var_label(t1) <- list(
AGE = "Age, years, ",
RAFEMALE = "Female",
race = "Race",
RAHISPAN = "Hispanic ethnicity",
poorhealth = "Fair or poor self-reported health",
PAIN = "Significant pain",
DIABETES = "Diabetes",
CANCER = "Cancer (excluding minor skin cancer)",
HEARTD = "Heart disease",
STROKE = "Stroke",
ARTHRITIS = "Arthritis",
DEPRESSION = "Depression",
SMOKING = "Ever tobacco use",
ADLhelp = "Help with any ADL",
cog_status = "Cognition",
BADVISION = "Visual impairment",
BADHEARING = "Hearing impairment",
local_area_litter = "Local area is full of rubbish and litter (≥4 on 1 to 7 scale)",
low_fin_control = "Low self-reported control over financial situation (≤3 on 0 to 10 scale)",
vet = "Military veteran",
combat = "Fired a weapon or been fired upon in combat",
LB039C = "Satisfaction with daily life and leisure activities (1 to 5 scale) ",
not_sat_retirement = "Not at all satisified with retirement",
edu = "High school graduate",
married = "Married or Partnered",
children = "No living children",
friends = "No friends",
LIVSIB = "Number of living siblings  ",
talk_with_someone = "Often has someone they can talk to",
LB001B = "Active with children (grandchildren, neighborhood children, nieces/nephews, 1 to 7 scale))",
never_charity_work = "Does no volunteering or charity work",
LB001F = "Goes to a sport, social, or other club (1 to 7 scale)",
children_lt_yearly = "Meet up with children less than once a year",
write_friends = "Write or email friends mothly or more frequently",
lonely = "Feel isolated from others",
z_in_tune  = "Often feel in tune with the people around you",
LB020J = "Feel part of a group of friends",
never_less_respect = "You are treated with less courtesy or respect than other people (never or less than once a year)",
never_not_smart = "People act as if they think you are not smart (never or less than once a year)",
WORK = "Currently working for pay"
)

library(tableone)
tab2 <- CreateTableOne(vars = myVars, strata = "YR", data = t1, factorVars = catVars)
tab2a <- print(tab2, nonnormal = not_nl, catDigits = 0, contDigits = 0, varLabels = TRUE, format = "fp", test = T, noSpace = TRUE, dropEqual = TRUE, printToggle = TRUE, quote = T, smd = TRUE)
 # tab2b <- tab2a[,1:3]
 # print(tab2b, quote = FALSE)


```

